### ISSUE TITLE
soilp and soilc filters for fates / non-fates?

### ISSUE THREAD

**Issue by rgknox** [ESCOMP/CTSM#1875] opened 2022-10-20 17:06 UTC
Moving forward, having FATES interact with CLM simultaneously with other models, such as crop model(s) or the big-leaf native CLM veg model, we identified that we should start filtering processes at the column and patch level.  

Mostly up to this point, we have used the "use_fates" global to decide if we want to do processes.  But we have started to slowly make use of column and patch level logical arrays like is_fates, to decid if we want to do things in patch and column loops.

It might be more efficient to take this one step further and create filters for high use cases.  For instance, we have filter_soilp and filter_soilc.  We could potentially have filter_soilp be a super set of filter_fates_soilp (all soil patches that are governed by fates) and filter_nonfates_soilp (all soil patches that are not governed by fates).  The benefit is that the code should be a little more streamlined and efficient (don't have to code in the logical statement ```if(patch%is_fates(p))then ```).  The downside, as I see it, is that with more filters, there could be more confusion, or more arrays that take up memory that aren't used much?  Thoughts?

**Comment by ekluzek** [comment] 2022-10-20 17:41
This makes a lot of sense to me. I think we should discuss this more, so I'm adding the next flag to it.

My only reaction right now is I'm not sure about the name filter_nonfates_soilp, the "nonfates" part should probably be something else. But, we don't have a good name to go there, as "bigleaf" isn't quite right. And actually this filter would apply for both BGC and SP modes, so the name needs to encompass both.

This also relates to these issues #1046 which presents essentially the same idea. And actually maybe we should close this one as a duplicate of it. Also #1051 relates to this as well.

**Closed** 2022-10-21 14:38 UTC
Labels: type: enhancement, type: -discussion, tag: next
