### ISSUE TITLE
Error building the case in CESM2.0

### ISSUE THREAD

**Issue by eolivares29** [ESCOMP/ctsm#805] opened 2019-09-17 21:04 UTC
I tried to build my case in CESM 2.0, but I get this error:
Building case in directory /general/home/eolivares/ef
sharedlib_only is False
model_only is False
Generating component namelists as part of build
Creating component namelists
   Calling /tiered/user/eolivares/components/cam//cime_config/buildnml
     ...calling cam buildcpp to set build time options
CAM namelist copy: file1 /general/home/eolivares/ef/Buildconf/camconf/atm_in file2 /scratch/user/eolivares/cesm/ef/ef/run/atm_in
   Calling /tiered/user/eolivares/components/clm//cime_config/buildnml
   Calling /tiered/user/eolivares/components/cice//cime_config/buildnml
     ...calling cice buildcpp to set build time options
File not found: grid_file = "/scratch/cesm/data/ocn/pop/gx1v7/grid/horiz_grid_20010402.ieeer8", will attempt to download in check_input_data phase
File not found: kmt_file = "/scratch/cesm/data/ocn/pop/gx1v7/grid/topography_20161215.ieeei4", will attempt to download in check_input_data phase
File not found: ice_ic = "/scratch/cesm/data/ice/cice/b.e15.B1850G.f09_g16.pi_control.25.cice.r.0041-01-01-00000.nc", will attempt to download in check_input_data phase
   Calling /tiered/user/eolivares/components/pop//cime_config/buildnml
     ...calling pop buildcpp to set build time options

     Log4perl: Seems like no initialization happened. Forgot to call init()?
   Calling /tiered/user/eolivares/components/mosart//cime_config/buildnml
   Running /tiered/user/eolivares/components/cism//cime_config/buildnml
Log4perl: Seems like no initialization happened. Forgot to call init()?
   Calling /tiered/user/eolivares/components/ww3//cime_config/buildnml
File not found: prestage_wind = "/scratch/cesm/data/wav/ww3/core2_G4_wns_30min_20000601_to_05.nc", will attempt to download in check_input_data phase
File not found: prestage_mod_def = "/scratch/cesm/data/wav/ww3/G4L1.mod_def.ww3.121031", will attempt to download in check_input_data phase
File not found: initfile = "/scratch/cesm/data/wav/ww3/restart.ww3.init.seed", will attempt to download in check_input_data phase
   Calling /tiered/user/eolivares/cime/src/components/stub_comps/sesp/cime_config/buildnml
   Calling /tiered/user/eolivares/cime/src/drivers/mct/cime_config/buildnml
File not found: atm2ocn_fmapname = "cpl/gridmaps/fv1.9x2.5/map_fv1.9x2.5_TO_gx1v7_aave.170518.nc", will attempt to download in check_input_data phase
File not found: atm2ocn_smapname = "cpl/gridmaps/fv1.9x2.5/map_fv1.9x2.5_TO_gx1v7_blin.170518.nc", will attempt to download in check_input_data phase
File not found: atm2ocn_vmapname = "cpl/gridmaps/fv1.9x2.5/map_fv1.9x2.5_TO_gx1v7_patc.170518.nc", will attempt to download in check_input_data phase
File not found: ocn2atm_fmapname = "cpl/gridmaps/gx1v7/map_gx1v7_TO_fv1.9x2.5_aave.170518.nc", will attempt to download in check_input_data phase
File not found: ocn2atm_smapname = "cpl/gridmaps/gx1v7/map_gx1v7_TO_fv1.9x2.5_aave.170518.nc", will attempt to download in check_input_data phase
File not found: atm2ice_fmapname = "cpl/gridmaps/fv1.9x2.5/map_fv1.9x2.5_TO_gx1v7_aave.170518.nc", will attempt to download in check_input_data phase
File not found: atm2ice_smapname = "cpl/gridmaps/fv1.9x2.5/map_fv1.9x2.5_TO_gx1v7_blin.170518.nc", will attempt to download in check_input_data phase
File not found: atm2ice_vmapname = "cpl/gridmaps/fv1.9x2.5/map_fv1.9x2.5_TO_gx1v7_patc.170518.nc", will attempt to download in check_input_data phase
File not found: ice2atm_fmapname = "cpl/gridmaps/gx1v7/map_gx1v7_TO_fv1.9x2.5_aave.170518.nc", will attempt to download in check_input_data phase
File not found: ice2atm_smapname = "cpl/gridmaps/gx1v7/map_gx1v7_TO_fv1.9x2.5_aave.170518.nc", will attempt to download in check_input_data phase
File not found: rof2ocn_fmapname = "cpl/gridmaps/r05/map_r05_TO_gx1v7_aave.161012.nc", will attempt to download in check_input_data phase
File not found: glc2ocn_liq_rmapname = "cpl/gridmaps/gland4km/map_gland4km_to_gx1v7_nn_open_ocean_nnsm_e1000r300_marginal_sea_171105.nc", will attempt to download in check_input_data phase
File not found: glc2ocn_ice_rmapname = "cpl/gridmaps/gland4km/map_gland4km_to_gx1v7_nnsm_e1000r300_171105.nc", will attempt to download in check_input_data phase
File not found: rof2ocn_liq_rmapname = "cpl/gridmaps/r05/map_r05_to_gx1v7_nn_open_ocean_nnsm_e1000r300_marginal_sea_170413.nc", will attempt to download in check_input_data phase
File not found: rof2ocn_ice_rmapname = "cpl/gridmaps/r05/map_r05_to_gx1v7_nnsm_e1000r300_170413.nc", will attempt to download in check_input_data phase
File not found: atm2wav_smapname = "cpl/gridmaps/fv1.9x2.5/map_fv1.9x2.5_TO_ww3a_bilin_140702.nc", will attempt to download in check_input_data phase
File not found: ocn2wav_smapname = "cpl/gridmaps/gx1v7/map_gx1v7_TO_ww3a_splice_170214.nc", will attempt to download in check_input_data phase
File not found: ice2wav_smapname = "cpl/gridmaps/gx1v7/map_gx1v7_TO_ww3a_splice_170214.nc", will attempt to download in check_input_data phase
File not found: wav2ocn_smapname = "cpl/gridmaps/ww3a/map_ww3a_TO_gx1v7_splice_170214.nc", will attempt to download in check_input_data phase
   NOTE: ignoring setting of glc2ice_rmapname=idmap in seq_maps.rc
Finished creating component namelists
Building gptl with output to file /scratch/user/eolivares/cesm/ef/ef/bld/gptl.bldlog.190917-154146
   Calling /tiered/user/eolivares/cime/src/build_scripts/buildlib.gptl
ERROR: /tiered/user/eolivares/cime/src/build_scripts/buildlib.gptl FAILED, cat /scratch/user/eolivares/cesm/ef/ef/bld/gptl.bldlog.190917-154146

I'd really appreciate if you guys have a solution for this.

Thanks,
Efrain O.

**Comment by billsacks** [comment] 2019-09-18 16:27
Please post this on the CESM forums, https://bb.cgd.ucar.edu/. When you do, please include everything you did, from your create_newcase line through running case.build. Also please include the contents of your gptl.bldlog file, since that seems to be the error. Since the problem is probably related to the port to your machine, please make sure you have followed the directions in http://esmci.github.io/cime/users_guide/porting-cime.html and, in your forum post, also describe what you have done to port CESM to your machine, including what you have added to config_compilers.xml and config_machines.xml. 

I'm going to go ahead and close this issue here, as this is not a CTSM issue.

**Closed by billsacks** 2019-09-18 16:27 UTC
