### ISSUE TITLE
Building/running with PGI fails on both hobart and cheyenne

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/ctsm#442] opened 2018-07-13 07:01 UTC
### General bug information

**CTSM version you are using:** ctsm1.0.dev002-1-g12435d4

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:**

Running with PGI compiler on either hobart (pgi/18.1) or cheyenne (pgi/17.9). Tried both BgcCrop and Sp configurations

### Details of bug

SMS_D.f10_f10_musgs.I2000Clm50BgcCropGs.cheyenne_pgi.clm-crop
SMS_D.f10_f10_musgs.I2000Clm50BgcCropGs.hobart_pgi.clm-crop
SMS_D_P1x1_Mmpi-serial.1x1_numaIA.I2000Clm50BgcCropGs.cheyenne_pgi.clm-crop

### Important details of your setup / configuration so we can reproduce the bug

Dies in CTSM initialization reading in mask from the domain file.

**Comment by jedwards4b** [comment] 2018-08-15 15:53
@ekluzek the details of bug here leaves something to be desired - how is it dying?   Do you get a traceback?

**Comment by ekluzek** [comment] 2018-08-15 17:08
OK, so I'm replicating my cases. I tried first on cheyenne, and it's failing in the build because it can't find a LINPACK subroutine. So that's a failure on our side in the build in cime. Here's the error in linking from the cesm.log. This is using ctsm1.0.dev008 which has cime5.6.10.

```
../../pgi/mpt/debug/nothreads/mct/noesmf/lib//libclm.a(SoilWaterMovementMod.o): In function `soilwatermovementmod_soilwater_moisture_form_':
SoilWaterMovementMod.F90:(.text+0x1e306): undefined reference to `dgtsv_'
../../pgi/mpt/debug/nothreads/mct/noesmf/lib//libclm.a(UrbBuildTempOleson2015Mod.o): In function `urbbuildtempoleson2015mod_buildingtemperature_':
UrbBuildTempOleson2015Mod.F90:(.text+0xd730): undefined reference to `dgesv_'
```

**Comment by jedwards4b** [comment] 2018-08-15 17:10
Right - so do you have the build you are reporting above?  That might make it easier to figure out the linpack problem.  It must have built then right?

**Comment by jedwards4b** [comment] 2018-08-15 18:13
That's not a pgi compiler issue.

**Comment by ekluzek** [comment] 2018-08-15 18:31
This case on hobart with ctsm1.0.dev008 dies at runtime in the CLM initialization (SMS_D.f10_f10_musgs.I2000Clm50BgcCrop.hobart_pgi.clm-crop). Giving


```
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 97903 RUNNING AT h027.cgd.ucar.edu
```
Case with DEBUG on or off act the same.

This case on hobart dies asking for memory at the same point in initialization: SMS_D_P1x1_Mmpi-serial.1x1_numaIA.I2000Clm50BgcCropGs.hobart_pgi.clm-crop. The same cases that die in initialization with PGI work on other compilers, so although it dies asking for memory the issue is that somehow the PGI compiler is asking for more memory than other compilers.

```
(seq_comm_printcomms)    28     0     1     1  CPLALLWAVID:
(seq_comm_printcomms)    29     0     1     1  WAV:
(seq_comm_printcomms)    30     0     1     1  CPLWAV:
(seq_comm_printcomms)    31     0     1     1  ALLESPID:
(seq_comm_printcomms)    32     0     1     1  CPLALLESPID:
(seq_comm_printcomms)    33     0     1     1  ESP:
(seq_comm_printcomms)    34     0     1     1  CPLESP:
0: ALLOCATE: 12803339104 bytes requested; not enough memory
```

Several older cases on cheyenne from July with ctsm1.0.dev002 builds ( SMS_D.f10_f10_musgs.I2000Clm50BgcCropGs.cheyenne_pgi.clm-crop, SMS_D_P1x1_Mmpi-serial.1x1_numaIA.I2000Clm50BgcCropGs.cheyenne_pgi.clm-crop, SMS_D.f10_f10_musgs.I2000Clm50SpGs.cheyenne_pgi.clm-default) but dies at initialization similarly. I'm going to retry those case again with the debugger DDT and report on what I see.

**Comment by jedwards4b** [comment] 2018-08-15 18:45
I'm sorry but this still doesn't indicate a compiler bug.  Is the calculation which is requesting nearly 13GB of memory on a single task correct?   I suspect it is not and you should pursue the source of that request.

**Comment by ekluzek** [comment] 2018-08-15 21:07
I'm moving the PGI build issue to a cime issue. I'll continue to work on the initialization memory issue separately here.

**Comment by ekluzek** [comment] 2018-08-15 22:52
The link issue has a fix for it with ESMCI/cime/#2753. I get the same out of memory issue, I'm looking more into it with the latest ctsm.

**Comment by ekluzek** [comment] 2018-08-16 05:14
OK, I tried with two other PGI compilers on cheyenne. It fails with both 17.5 and 17.9 in the same way, but works with 16.5.

**Comment by jedwards4b** [comment] 2018-08-16 14:36
I have traced the problem in the SMS_D_P1x1_Mmpi-serial.1x1_numaIA.I2000Clm50BgcCropGs.cheyenne_pgi.clm-crop case to the call to
   call urbantv_inst%Init(bounds, NLFilename)   
in file clm_instMod.F90 it seems to be failing on the subroutine interface.

**Comment by jedwards4b** [comment] 2018-08-17 15:31
@ekluzek 
It appears that the case SMS_D_P1x1_Mmpi-serial.1x1_numaIA.I2000Clm50BgcCropGs.gauss_pgi.clm-crop can only be run on cheyenne since the required inputdata is not available from the svn server.  Is there a way to reproduce this with data on the server?

**Comment by ekluzek** [comment] 2018-08-17 15:44
@jedwards4b I'll figure out what data is missing and add it to input data. Probably just the surface dataset.

**Comment by ekluzek** [comment] 2018-08-17 16:08
@jedwards4b OK I looked at the clm data, and it all seems to be in svn inputdata. What I'm guessing that you are missing is the forcing data for gauss. If it's not automatically downloading the forcing data that means that the path to $DIN_LOC_ROOT_CLMFORC is wrong for the machine. On a standard machine $DIN_LOC_ROOT_CLMFORC=$DIN_LOC_ROOT/atm/datm7/, but on some machines like cheyenne we have to point to a different location for the forcing data since it's large. And because of that the automatic download doesn't work on cheyenne. I think it works in the first instance of DIN_LOC_ROOT_CLMFORC that I gave though.

Is it the forcing data that's missing? Am I correct on that? To make the download faster you could just download a year (making some changes in env variables so it only needs a year). And the Qian data is smaller, so you could just get a year of it.

**Comment by jedwards4b** [comment] 2018-08-17 16:33
@ekluzek Yes, it's the forcing data: Why should we require a year of data for a 5 day test?

**Comment by ekluzek** [comment] 2018-08-17 17:44
@jedwards4b it's the way the system is currently setup and with how streams work in datm/cime. In the streams namelist you give the year start and end so it will expect to download data for that entire year. You could hack it to get around that, by changing the streams file by hand. But you would have to hack it for it to even work. And since we never operate that way, I would be surprised if there was NOT unforeseen problems. Grabbing a single year won't be that bad though. While grabbing the whole set of data would be days of downloading.

**Comment by jedwards4b** [comment] 2018-09-28 19:10
Update from Brent Leback of PGI: The fix is in our dev compiler. Scheduled to get into our next release, 18.10, which is also a community edition compiler.

**Comment by jedwards4b** [comment] 2018-09-28 19:13
More info from Brent: It’s about a month out.  Supposed to be the October release, but for several reasons, the CE releases end up getting released around the last day of the month.

**Comment by billsacks** [comment] 2019-08-30 03:44
The failing tests pass on izumi, which uses pgi 18.10.

pgi tests will still fail on hobart, but since we're moving our testing from hobart to izumi, I'm closing this as a wontfix.

**Closed by billsacks** 2019-08-30 03:44 UTC
Labels: type: bug
