### ISSUE TITLE
Some python system tests are failing (lilac build python tests)

### ISSUE THREAD

**Issue by negin513** [ESCOMP/CTSM#1739] opened 2022-05-05 20:52 UTC
### Brief summary of bug

I was just testing python unit tests for PR #1727 and noticed some LILAC related unit tests are failing with a . I am not sure what is causing this issue. This is the error that I am getting from running `make` in `python/` directory:
```
EERROR: Current machine cheyenne does not match case machine ctsm-build.
```
The complete error is attached below.

### General bug information

**CTSM version you are using:** ctsm5.1.dev091

### Details of bug
```
python3 ./run_ctsm_py_tests  --unit
.....................................................................................................................
----------------------------------------------------------------------
Ran 117 tests in 0.210s

OK
python3 ./run_ctsm_py_tests  --sys
...ERROR: Current machine cheyenne does not match case machine ctsm-build.
EERROR: Current machine cheyenne does not match case machine ctsm-build.
E
======================================================================
ERROR: test_buildSetup_userDefinedMachine_allInfo (test.test_sys_lilac_build_ctsm.TestSysBuildCtsm)
Get through the case.setup phase with a user-defined machine
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/glade/scratch/negins/ctsm_1707/python/ctsm/test/test_sys_lilac_build_ctsm.py", line 90, in test_buildSetup_userDefinedMachine_allInfo
    inputdata_path=os.path.join(self._tempdir, 'my_inputdata'))
  File "/glade/scratch/negins/ctsm_1707/python/ctsm/lilac_build_ctsm.py", line 180, in build_ctsm
    inputdata_path=inputdata_path)
  File "/glade/scratch/negins/ctsm_1707/python/ctsm/lilac_build_ctsm.py", line 619, in _create_case
    subprocess.check_call([xmlchange, 'LILAC_MODE=on'], cwd=case_dir)
  File "/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/glade/scratch/negins/tmpm9i4wv5c/ctsm_build/case/xmlchange', 'LILAC_MODE=on']' returned non-zero exit status 1.

======================================================================
ERROR: test_buildSetup_userDefinedMachine_minimalInfo (test.test_sys_lilac_build_ctsm.TestSysBuildCtsm)
Get through the case.setup phase with a user-defined machine
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/glade/scratch/negins/ctsm_1707/python/ctsm/test/test_sys_lilac_build_ctsm.py", line 53, in test_buildSetup_userDefinedMachine_minimalInfo
    no_pnetcdf=True)
  File "/glade/scratch/negins/ctsm_1707/python/ctsm/lilac_build_ctsm.py", line 180, in build_ctsm
    inputdata_path=inputdata_path)
  File "/glade/scratch/negins/ctsm_1707/python/ctsm/lilac_build_ctsm.py", line 619, in _create_case
    subprocess.check_call([xmlchange, 'LILAC_MODE=on'], cwd=case_dir)
  File "/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/glade/scratch/negins/tmpha5_r97c/ctsm_build/case/xmlchange', 'LILAC_MODE=on']' returned non-zero exit status 1.

----------------------------------------------------------------------
Ran 5 tests in 4.578s

FAILED (errors=2)
pylint -j 4 --rcfile=ctsm/.pylintrc ctsm

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)

```

**Comment by ekluzek** [comment] 2022-05-05 21:55
Ahhh, I'm glad you filed this as I noticed it and thought it was a problem in my PR.

I checked a few different versions and narrowed it down to starting in ctsm5.1.dev086 (works in dev085 and fails in dev086 and following). The only thing I see in going from dev085 to dev086 are some external updates. So I think it might be due to the change from cime6.013 to cime6.0.15

**Comment by ekluzek** [comment] 2022-05-05 21:57
It looks like the issue is when going from cime6.0.13 to cime6.0.14. Just changing the version in dev086 shows the problem.

**Comment by billsacks** [comment] 2022-05-05 21:59
Hold off on spending more time on this: I'm pretty sure I ran into this recently and fixed it, but just am trying to figure out where that fix went....

**Comment by ekluzek** [comment] 2022-05-05 22:00
OK, cool. I did start a git bisect. But, I'll let you see if you can find your solution.

**Comment by ekluzek** [comment] 2022-05-05 22:53
I've verified that bringing in #1740 into my PR for #1723 solves the issue. So now the python tests work for me. So I'll bring the fix for this in that PR, since it requires a cime update.

**Closed** 2022-05-09 11:03 UTC
