### ISSUE TITLE
broken links in user guide about namelist hist_fincl

### ISSUE THREAD

**Issue by evalieungh** [ESCOMP/CTSM#1680] opened 2022-03-09 10:56 UTC
Hi!
I was reading about namelist changes and output history files, but got stuck at two broken links (404 error) about hist_fincl in this section:
<https://escomp.github.io/ctsm-docs/versions/release-clm5.0/html/users_guide/setting-up-and-running-a-case/customizing-the-clm-namelist.html?highlight=hist_fincl#list-of-fields-that-can-be-added-to-your-output-history-files-by-namelist>

The following two links are broken: 

[CLM4.0 History Fields](https://escomp.github.io/ctsm-docs/versions/release-clm5.0/html/users_guide/setting-up-and-running-a-case/CLM-URL) and [|version| History Fields](https://escomp.github.io/ctsm-docs/versions/release-clm5.0/html/users_guide/setting-up-and-running-a-case/CLM-URL)

Does someone know which pages those links were supposed to point to?

**Comment by ekluzek** [comment] 2022-03-09 22:13
Thanks for pointing this out. This is a known issue and unfortunately not something we've been able to get do.


This is a duplicate of #1522

**Comment by ekluzek** [comment] 2022-03-09 22:14
Closing as this is a duplicate.

**Closed by ekluzek** 2022-03-09 22:14 UTC
Labels: closed: duplicate
