### ISSUE TITLE
gptl build error: error: macro names must be identifiers

### ISSUE THREAD

**Issue by serbinsh** [ESCOMP/ctsm#652] opened 2019-03-06 15:59 UTC
### Brief summary of bug
```
/ctsm_output/CLM5FATES_1551887180_1x1brazil/bld/gptl.bldlog.190306-154632
gmake -f /ctsm/cime/src/share/timing/Makefile install -C /ctsm_output/CLM5FATES_1551887180_1x1brazil/bld/gnu/openmpi/nodebug/nothreads/gptl MACFILE=/ctsm_output/CLM5FATES_1551887180_1x1brazil/Macros.make MODEL=gptl GPTL_DIR=/ctsm/cime/src/share/timing GPTL_LIBDIR=/ctsm_output/CLM5FATES_1551887180_1x1brazil/bld/gnu/openmpi/nodebug/nothreads/gptl SHAREDPATH=/ctsm_output/CLM5FATES_1551887180_1x1brazil/bld/gnu/openmpi/nodebug/nothreads
gmake: Entering directory '/ctsm_output/CLM5FATES_1551887180_1x1brazil/bld/gnu/openmpi/nodebug/nothreads/gptl'
mpicc   -c -I/ctsm/cime/src/share/timing  -std=gnu99   -O    -D  -DFORTRANUNDERSCORE -DNO_R16 -DCPRGNU  -DHAVE_VPRINTF -DHAVE_GETTIMEOFDAY -DHAVE_BACKTRACE  -DHAVE_MPI /ctsm/cime/src/share/timing/gptl.c
/ctsm/cime/src/share/timing/Makefile:55: recipe for target 'gptl.o' failed
gmake: Leaving directory '/ctsm_output/CLM5FATES_1551887180_1x1brazil/bld/gnu/openmpi/nodebug/nothreads/gptl'
<command-line>:0:1: error: macro names must be identifiers
/ctsm/cime/src/share/timing/gptl.c: In function 'GPTLpr_summary_file':
/ctsm/cime/src/share/timing/gptl.c:3090:8: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   if (((int) comm) == 0)
        ^
gmake: *** [gptl.o] Error 1
ERROR: <command-line>:0:1: error: macro names must be identifiers
/ctsm/cime/src/share/timing/gptl.c: In function 'GPTLpr_summary_file':
/ctsm/cime/src/share/timing/gptl.c:3090:8: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   if (((int) comm) == 0)
        ^
gmake: *** [gptl.o] Error 
```
### General bug information

**CTSM version you are using:** clm5.0.dev008-88-ge862304
FATES: sci.1.23.0_api.7.1.0

```
commit e8623043e3365e86c2cecea1d475324e9a8e2da3
Merge: 5af5787 22623ea
Author: Ryan Knox <rgknox@lbl.gov>
Date:   Mon Feb 11 10:49:19 2019 -0700

    Merge pull request #632 from rgknox/rgknox-leafage-params

    update default fates parameter file
```

**Does this bug cause significantly incorrect results in the model's science?** [Yes / No] NA

**Configurations affected:** [Fill this in if known.] NA

### Details of bug

above

### Important details of your setup / configuration so we can reproduce the bug

[Specify anything relevant: the compset, resolution, machine, compiler, any xml or namelist changes, etc. You don't have to repeat anything that you have already noted above.]

1x1_brazil
I2000Clm50FatesGs

**Comment by serbinsh** [comment] 2019-03-06 16:00
```
gcc --version
gcc (GCC) 6.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
mpiCC --version
g++ (GCC) 6.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by billsacks** [comment] 2019-03-06 16:27
@serbinsh can you please move this issue to https://github.com/esmci/cime since this is related to cime rather than ctsm itself? Ideally you would reproduce this issue with an A or X compset in cime.

I'm going to close it here.

**Closed by billsacks** 2019-03-06 16:27 UTC

**Comment by serbinsh** [comment] 2019-03-06 16:50
Done.  I make this mistake regularly because I forget that build=cime and physics=ctsm.  And in this case its probably a CIME version issue in the CTSM fates_next_api branch

https://github.com/ESMCI/cime/issues/3027
