### ISSUE TITLE
levsno mismatch in FATES run

### ISSUE THREAD

**Issue by rgknox** [ESCOMP/ctsm#308] opened 2018-02-28 19:47 UTC
The following test:

ERS_Ld3.f45_f45_mg37.I2000Clm50Fates.hobart_pgi.hobart_pgi_f45

Generates a run-time error related to levsno.

Error snippet:

```
heck_dim ERROR: mismatch of input dimension             5 
  with expected value            12application called MPI_Abort(MPI_COMM_WORLD, 1001) - process 0
  for variable levsno
You can deal with this mismatch by rerunning with use_init_interp = .true. in user_nl_clm
 ERROR: ERROR in /home/rgknox/ctsm/src/main/ncdio_pio.F90.in at line 368
application called MPI_Abort(MPI_COMM_WORLD, 1001) - process 13
 check_dim ERROR: mismatch of input dimension             5 
  with expected value            12  for variable levsno
You can deal with this mismatch by rerunning with use_init_interp = .true. in user_nl_clm
 ERROR: ERROR in /home/rgknox/ctsm/src/main/ncdio_pio.F90.in at line 368
application called MPI_Abort(MPI_COMM_WORLD, 1001) - process 17

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 30290 RUNNING AT h022.cgd.ucar.edu
=   EXIT CODE: 233
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================

```

CTSM hash: 2dba0746
Fates hash: (HEAD detached at fates_s1.4.1_a3.0.0_rev3) 52bad28

**Comment by rgknox** [comment] 2018-02-28 19:49
Note: myself, nor anyone else with FATES uses hobart regularly, I just like testing with PGI, so this may not be high priority, unless we learn something from it I suppose...

**Comment by rgknox** [comment] 2018-02-28 19:51
noting discussion in #76

**Comment by billsacks** [comment] 2018-02-28 19:51
It looks like the problem is that this configuration is pointing to an old initial conditions file, or perhaps one generated with CLM45 physics. It used to be (and still is for clm45) that there were 5 snow layers; now in clm5 there are 12. Since you can't run init_interp with FATES, I think the solution is to point to a more recent CLM5 initial conditions file here, or else use cold start.

**Comment by rgknox** [comment] 2018-02-28 19:56
ahhh, thats right @billsacks , now I recall that we have been doing coldstart with FATES for the time being.  I can re-try my test with cold start.
I'm thinking though that it might be a good idea for me to put in some time getting init_interp working on fates.

**Comment by dlawrenncar** [comment] 2018-02-28 20:08
Init_interp is a big  life/time saver.  Getting it working in FATES may be
quite beneficial as we work to move towards using FATES more regularly and
by more users.

**Comment by ekluzek** [comment] 2018-03-02 18:35
I'm closing this as it's a duplicate of #221. And yes it also relates to #76.

**Closed by ekluzek** 2018-03-02 18:35 UTC
Labels: status: duplicate, status: wontfix, type: bug - other
