### ISSUE TITLE
htop too low with Meier roughness on for BGC for transient after a year

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#2234] opened 2023-11-05 03:04 UTC
### Brief summary of bug

Following test fails on the CESM3_dev branch

ERS_Ly5_P144x1.f10_f10_mg37.IHistClm51BgcCrop.cheyenne_intel.clm-cropMonthOutput

### General bug information

**CTSM version you are using:** branch_tags/CESM3_dev.n02_ctsm5.1.dev145-2-geb3c74cff

**Does this bug cause significantly incorrect results in the model's science?** ?

**Configurations affected:** 

Looks like it needs to be transient on the year boundary with BGC on. Does it also need Crop on?

### Details of bug

This happens after running a year

### Important output or errors that show the problem

cesm.log
``` text
139:iam = 139: column   type         = 278
139:iam = 139: landunit type         = 2
139: ENDRUN:
139: ERROR: ERROR in BiogeophysPreFluxCalcsMod.F90 at line 203
139:Image              PC                Routine            Line        Source
139:cesm.exe           00000000013CCF96  Unknown               Unknown  Unknown
139:cesm.exe           000000000100A770  shr_abort_mod_mp_         114  shr_abort_mod.F90
139:cesm.exe           00000000005CF6B1  abortutils_mp_end          98  abortutils.F90
139:cesm.exe           00000000007992A7  biogeophyspreflux         203  BiogeophysPreFluxCalcsMod.F90
139:cesm.exe           00000000005D943A  clm_driver_mp_clm         644  clm_driver.F90
139:cesm.exe           0000000000585962  lnd_comp_nuopc_mp         904  lnd_comp_nuopc.F90
```

**Comment by ekluzek** [comment] 2023-11-05 03:06
Shorter tests seem to be fine. For example...

ERP_D.f10_f10_mg37.IHistClm51Bgc.cheyenne_gnu.clm-decStart
ERP_D.f10_f10_mg37.IHistClm51Bgc.cheyenne_intel.clm-decStart
ERP_P36x2_Lm13.f10_f10_mg37.IHistClm51Bgc.cheyenne_gnu.clm-monthly
ERP_P36x2_Lm13.f10_f10_mg37.IHistClm51Bgc.cheyenne_intel.clm-monthly

A three year test also passes that's not transient:

ERS_Ly3.f10_f10_mg37.I2000Clm51BgcCrop.cheyenne_intel.clm-Meier2022_surf_rough

**Comment by ekluzek** [comment] 2023-11-05 03:08
The part where it fails is as follows in src/biogeophys/BiogeophysPreFluxCalcsMod.F90:

``` fortran
               if ( htop(p) <= 1.e-10_r8 )then
                   write(iulog,*) ' nstep = ', get_nstep(), ' htop = ', htop(p)
                   call endrun(subgrid_index=p, subgrid_level=subgrid_level_patch, msg=errMsg(sourcefile, __LINE__))
```

**Comment by ekluzek** [comment] 2023-11-05 03:23
This test also fails with the same issue:

LCISO_Lm13.f10_f10_mg37.IHistClm51BgcCrop.cheyenne_intel.clm-ciso_monthly

**Comment by slevis-lmwg** [comment] 2023-11-28 18:44
Closing as duplicate of #2264.
Thank you for pointing this out @ekluzek.

**Closed by slevis-lmwg** 2023-11-28 18:44 UTC
Labels: type: bug
