### ISSUE TITLE
Change hist_type2d_pertape to hist_type1d_pertape in User's Guide

### ISSUE THREAD

**Issue by olyson** [ESCOMP/CTSM#2509] opened 2024-05-02 15:33 UTC
Change hist_type2d_pertape to hist_type1d_pertape in User's Guide.  hist_type2d_pertape isn't a valid namelist variable.
https://escomp.github.io/ctsm-docs/versions/master/html/users_guide/setting-up-and-running-a-case/customizing-the-clm-namelist.html?highlight=hist_type2d_pertape

**Comment by samsrabin** [comment] 2024-09-16 19:22
Closing as a duplicate of #103.

**Closed by samsrabin** 2024-09-16 19:22 UTC
Labels: documentation
