### ISSUE TITLE
allActive test fails starting in clm4_5_18_r275

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/ctsm#302] opened 2018-02-16 18:36 UTC
This test case "ERP_D_Ld5.f10_f10_musgs.I2000Clm50BgcCrop.cheyenne_intel.clm-allActive" started failing in clm4_5_18_r275. Floating invalid in SoilFluxesMod.F90 as follows...

```
0:   Creating variable uvel
0:   Creating variable vvel
0:    Writing to file ERP_D_Ld5.f10_f10_musgs.I2000Clm50BgcCrop.cheyenne_intel.clm
0: -allActive.C.radtmpn05_d001chintelaux.cism.initial_hist.0001-01-01-00000.nc at 
0: time   0.000000000000000E+000
6:forrtl: error (65): floating invalid
6:Image              PC                Routine            Line        Source             
6:cesm.exe           0000000004A5A5F1  Unknown               Unknown  Unknown
6:cesm.exe           0000000004A5872B  Unknown               Unknown  Unknown
6:cesm.exe           0000000004A09FF4  Unknown               Unknown  Unknown
6:cesm.exe           0000000004A09E06  Unknown               Unknown  Unknown
6:cesm.exe           0000000004976CC9  Unknown               Unknown  Unknown
6:cesm.exe           0000000004982E1C  Unknown               Unknown  Unknown
6:libpthread-2.19.s  00002AAAAFAC1870  Unknown               Unknown  Unknown
6:cesm.exe           0000000001F80165  soilfluxesmod_mp_         540  SoilFluxesMod.F90
6:cesm.exe           0000000000897280  clm_driver_mp_clm         670  clm_driver.F90
6:libiomp5.so        00002AAAAEECCD13  __kmp_invoke_micr     Unknown  Unknown
6:libiomp5.so        00002AAAAEE9CFAD  __kmp_fork_call       Unknown  Unknown
6:libiomp5.so        00002AAAAEE756F8  __kmpc_fork_call      Unknown  Unknown
6:cesm.exe           0000000000882355  clm_driver_mp_clm         395  clm_driver.F90
6:cesm.exe           000000000084FD26  lnd_comp_mct_mp_l         451  lnd_comp_mct.F90
6:cesm.exe           000000000046CCC1  component_mod_mp_         688  component_mod.F90
6:cesm.exe           000000000043D259  cime_comp_mod_mp_        2652  cime_comp_mod.F90
```

**Comment by billsacks** [comment] 2018-02-28 21:02
@ekluzek I can't reproduce this problem. From poking around in your directories, it looks to me like you've just been having this fail from the radtemp branch, so I'm thinking the problem is specific to that branch.

I'm going to close this issue; feel free to reopen if you feel this truly is a problem on master.

**Closed by billsacks** 2018-02-28 21:02 UTC
Labels: priority: high, severity: critical, type: bug - other
