### ISSUE TITLE
Change end year for ndep for SSP's to 2101

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/ctsm#717] opened 2019-05-17 17:31 UTC
### Brief summary of bug

We need to change the end year for ndep for the SSP's to 2101, so that it will run through the end of the year for 2100.

### General bug information

**CTSM version you are using:** branch_tags/relcisofix.n01_release-clm5.0.20
**Does this bug cause significantly incorrect results in the model's science?** [Yes / No]

**Configurations affected:** All SSP's

### Details of bug

The end year for the SSP's for ndep is 2100, it should be changed to 2101 so that you can run to the end of 2100. Here's the line in the namelist_defaults_clm4_5.xml file that needs to change...

`<stream_year_last_ndep  phys="clm5_0" use_cn=".true." sim_year_range="1850-2100"  >2100</stream_year_last_ndep>`

### Important details of your setup / configuration so we can reproduce the bug

This was found in the BSSP126cmip6 compset for CMIP6

### Important output or errors that show the problem

This is the error message that Nan Rosenblum got...

It crashed on Dec-16-2100 of my 2100 year SSP126 simulation.

>  clm: completed timestep      1505976
> 
> (shr_dmodel_readstrm) file ub: /glade/p/cesmdata/cseg/inputdata/lnd/clm2/ndepdata/fndep_clm_SSP126_b.e21.BWSSP126cmip6.f09_g17.CMIP6-SSP1-2.6-WACCM.001_2014-2101_monthly_0.9x1.25_c190221.nc       1
> 
>  (shr_strdata_advance) ERROR: for stream            1
> 
>  (shr_strdata_advance) ERROR: dt limit1    59891.0000000000     
> 
>    29.5000000000000        1.50000000000000     
> 
>  (shr_strdata_advance) ERROR: dt limit2     21001216       43200    22650116
> 
>        43200
> 
>  ERROR: (shr_strdata_advance) ERROR dt limit for stream

**Comment by klindsay28** [comment] 2019-05-17 19:26
@ekluzek, I'm curious about why the CESM2 CMIP6 ssp585 experiments didn't have this problem.

The ndep nml vars from the ssp585 experiments are
```model_year_align_ndep = 2015
 ndep_taxmode = 'extend'
 ndep_varlist = 'NDEP_month'
 ndepmapalgo = 'bilinear'
 stream_fldfilename_ndep = '/glade/p/cesmdata/cseg/inputdata/lnd/clm2/ndepdata/fndep_clm_SSP585_b.e21.BWSSP585cmip6.f09_g17.CMIP6-SSP5-8.5-WACCM.001_2014-2101_monthly_0.9x1.25_c190211.nc'
 stream_year_first_ndep = 2015
 stream_year_last_ndep = 2100
```

The ndep nml vars from the ssp126 experiment, with `stream_year_last_ndep=2101` in user_nl_clm, are
```model_year_align_ndep = 1850
 ndep_taxmode = 'cycle'
 ndep_varlist = 'NDEP_month'
 ndepmapalgo = 'bilinear'
 stream_fldfilename_ndep = '/glade/p/cesmdata/cseg/inputdata/lnd/clm2/ndepdata/fndep_clm_SSP126_b.e21.BWSSP126cmip6.f09_g17.CMIP6-SSP1-2.6-WACCM.001_2014-2101_monthly_0.9x1.25_c190221.nc'
 stream_year_first_ndep = 1850
 stream_year_last_ndep = 2101
```

The ssp585 experiment is using ctsm tag release-clm5.0.20.
The ssp126 experiment is using branch_tags/relcisofix.n01_release-clm5.0.20.

Is the change to `ndep_taxmode` intentional?

Was the ssp585 experiment, using `ndep_taxmode='extend'`, run properly?

I'm partly curious because I'm now running an ssp585 experiment (with prognostic carbon cycle). The experiment that I'm running is using branch_tags/relcisofix.n01_release-clm5.0.20, and it has ndep nml vars
```model_year_align_ndep = 1850
 ndep_taxmode = 'cycle'
 ndep_varlist = 'NDEP_month'
 ndepmapalgo = 'bilinear'
 stream_fldfilename_ndep = '/glade/p/cesmdata/cseg/inputdata/lnd/clm2/ndepdata/fndep_clm_SSP585_b.e21.BWSSP585cmip6.f09_g17.CMIP6-SSP5-8.5-WACCM.001_2014-2101_monthly_0.9x1.25_c190211.nc'
 stream_year_first_ndep = 1850
 stream_year_last_ndep = 2100
```
I suspect that I will need to add `stream_year_last_ndep=2101` or `ndep_taxmode='extend'` to user_nl_clm in this experiment. I'm not sure which change is preferable.

**Comment by ekluzek** [comment] 2019-05-17 19:55
@klindsay28 the change on ndep_taxmode to extend was intentional and is discussed in #700.

I suspect that the RCP5-8.5 case is likely doing the wrong thing at the end of 2100, by using the beginning of the time-series Jan-2015 to tie off the end of Dec/2100. We should check and see if that's the case, but it's pretty certain it is. That's definitely not the right thing to do, so the change to year end to 2101 is the right thing to do.

**Comment by olyson** [comment] 2019-05-17 20:05
I looked at the lnd log file for b.e21.BSSP585cmip6.f09_g17.CMIP6-SSP5-8.5.001 and don't see any indication that it is looping back to 2015.  Since ndep_taxmode is = 'extend' that's what I would expect, but correct me if I'm wrong.

**Comment by ekluzek** [comment] 2019-05-17 20:10
OK, I was thinking it was cycle -- rather than extend. Some of @klindsay28 examples above have cycle in them. So the SSP585 case should just stay with the Dec/2100 value (which is what extend does), but the SSP126 case and @klindsay28 new SSP585 experiment -- probably wrongly cycle back to the beginning of the series.

**Comment by olyson** [comment] 2019-05-17 20:14
Since Nan changed to stream_year_last_ndep = 2101, it will use Jan 2101 to interpolate from, not 2015.  I confirmed this by looking at the log file.

**Comment by klindsay28** [comment] 2019-05-17 21:13
It looks like the ssp126 experiment was run with a more recent tag than the ssp585 experiment, and the ssp126 experiment has `ndep_taxmode = 'cycle'`.

My reading of the conversation in #700 is that it suggests `ndep_taxmode = 'limit'`.

So I'm a bit confused about how `ndep_taxmode` is intended to be set.

**Comment by olyson** [comment] 2019-05-17 21:59
The ssp126 experiment had 'cycle' (which is the default).  The SSP585 had 'extend' because it had that in the user_nl_clm.
Erik has put 'limit' in a recent tag so that the model throws an error if it tries to loop back to 2015 when it reaches the end of the data.  But none of the current runs Nan is doing are using this more recent tag.
In any case, if stream_year_last_ndep=2101, it doesn't matter what ndep_taxmode is as long as the model is only run through the end of 2100.

**Comment by olyson** [comment] 2019-05-18 00:22
So, I think that if you want to replicate the SSP585 experiment, you  would do this:
ndep_taxmode = 'extend'
And leave this as is:
stream_year_last_ndep = 2100
Dec 16 - 31, 2100 would then use the Dec, 2100 mid-month value from the ndep file without interpolation.
The SSP585 ensemble members are self_consistent with this.

The other SSP simulations will be interpolating between the Dec, 2100 value and the Jan, 2101 value because of this setting:
stream_year_last_ndep = 2101
However, the 2101 values in the file are simply a duplication of the 2100 values.

**Comment by klindsay28** [comment] 2019-05-18 12:37
Thanks for the clarifications @olyson

**Closed** 2019-05-22 20:31 UTC
Labels: branch tag: release, priority: high, type: bug - other
