### ISSUE TITLE
cannot successfully run py_env_create on derecho

### ISSUE THREAD

**Issue by mvertens** [ESCOMP/CTSM#2674] opened 2024-07-31 20:48 UTC
### Brief summary of bug

I am using ctsm5.2.008 and trying to run ./py_env_create on derecho. I need this capability to create a new ctsm surface dataset.
I also tried this on the NorESM platform betzy and got the same behavior. Can someone please point me to a fix or a setup that I can use.

### General bug information
I get the following error output

$ ./py_env_create
Use conda to install the python environment needed to run the CTSM python tools in the conda environment: ctsm_pylib
```
Using the file: ./python/conda_env_ctsm_py.txt
ctsm_pylib environment already exists
Install ctsm_pylib this can take a long time (12 to 20 minutes is expected), be patient....
    ....
    ....
    ....
conda install --yes --quiet --channel conda-forge --name ctsm_pylib ./python/conda_env_ctsm_py.txt
Channels:
 - conda-forge
 - r
Platform: linux-64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

PackagesNotFoundError: The following packages are not available from current channels:

  - ./python/conda_env_ctsm_py.txt

Current channels:

  - https://conda.anaconda.org/conda-forge
  - https://conda.anaconda.org/r

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


Trouble installing the ctsm_pylib python environment
There must be a problem in the ./python/conda_env_ctsm_py.txt conda specification environment file
Change the file and try again
```
**CTSM version you are using: ctsm5.2.008

**Does this bug cause significantly incorrect results in the model's science?No

### Details of bug
See above

**Comment by ekluzek** [comment] 2024-07-31 20:55
This is a duplicate of #2563 which was fixed in ctsm5.2.011. Merging the PR (#2607) that brought that in should fix this for you.

**Closed** 2024-08-01 07:54 UTC
Labels: closed: duplicate
