### ISSUE TITLE
Modified NEON surface datasets have errors 

### ISSUE THREAD

**Issue by wwieder** [ESCOMP/CTSM#1429] opened 2021-07-15 17:40 UTC
### Brief summary of bug

It looks like a few sites that use the modified NEON surface dataset end up with errors in the soil sand, clay, and ORGANIC profiles.  

### General bug information
A quick look at some sites suggest this is an issue for HEAL, PUUM, TOOL and maybe others?  We don't even have met data for most of these sites, so it's likely not a big issue at this point, but something to be aware of as we start running more sites

@negin513 confirmed this is not an issue with how we're handling `zbedrock`, but results from issues in the raw data from NEON.

**Does this bug cause significantly incorrect results in the model's science?** YES

@ekluzek I don't want to delay bringing in #1375 and #1411, so let's bring in these PRs and @negin513 can address this later.

**Configurations affected:** NEON tower simulations

**Comment by negin513** [comment] 2021-07-16 03:32
Will, thanks for bringing this up to my attention. 
It seems like the issue of missing data in the updated surface dataset is not related to `zbedrock` and **it is caused by missing data in the provided neon surface dataset.** 

As we discussed earlier, you made [an issue](https://github.com/NEONScience/NCAR-NEON/issues/44) about this on NEON repo.

**Comment by negin513** [comment] 2021-07-16 03:36
@wwieder:
 Since this does not seem to be caused by any bugs related to the code, should we close this issue and continue the discussion in the corresponding [NEON issue](https://github.com/NEONScience/NCAR-NEON/issues/44).

**Comment by wwieder** [comment] 2021-07-16 12:56
@negin513 let's leave this open to discuss how we want to handle this on the NCAR side.

It seems like there are three issue here

1. **Missing values**, I wonder what others think about @ekluzek's suggestion to fill in missing data from NEON with the default values from the orig. surface dataset
2. **Organic horizons**, especially in some forest sites this gives really large ORGANIC surface soil layers (e.g. HARV or ORNL). Do we leave this feature, or replace O horizon data with A horizon data for consistency?   I suggest we leave these data and evaluate impacts on moisture and temperature dynamics with the two surface datasets.
3. **Crazy values**,  especially at depth (e.g. ONAQ). These will take a case-by case evaluation to identify potential issues with raw data (e.g. bulk density) in the data NEON are providing, but it's likely important to QC the NEON data.

**Comment by wwieder** [comment] 2021-07-16 20:46
This [sheet has a summary](https://docs.google.com/spreadsheets/d/1pkqeQExcamryh8SWJCdEjbE9LakbEUoFQu1TK8je5T8/edit?usp=sharing) of good, bad, and suspect data

**Comment by dlawrenncar** [comment] 2021-07-19 15:27
Note that the O-horizon is 'applied' through organic matter content.
Sand/silt/clay texture is generally always set for all layers, but will not
be used if organic matter is at the maximum value.

**Comment by wwieder** [comment] 2021-07-19 16:17
Thanks for clarifying @dlawrenncar. it doesn't look like the HWSD and NCSCD used for `ORGANIC` typically included highly organic 'litter' layers in model.  Do you agree with the suggestion of # 2 above, that leave in the high organic values from NEON observations and evaluate simulated temperature and moisture profiles?

**Comment by dlawrenncar** [comment] 2021-07-19 16:51
Yes.  I agree with that idea to compare the two.  When the organic matter
being referred to is actually a litter layer, CTSM doesn't really have a
mechanism to account for this presumably seasonally varying situation.

**Comment by wwieder** [comment] 2021-08-12 15:39
more work is needed here to fill gaps in data and correct `organic` calculation.

**Comment by wwieder** [comment] 2021-09-21 20:43
The notes on @jedwards4b's latest [sheet with the status of sites](https://docs.google.com/spreadsheets/d/1Q8tbUdKRBI7VhSMXOct7Hx0G5xoWPXsTxyayQX3OiFk/edit#gid=0) still points to a surface data issue with KONA: 
- [but I don't see why](https://drive.google.com/drive/folders/1nuuVRtmISa-lnMHsZ1KrfQp4K3PB7uEa)?  
- I also don't see any [missing data](https://neon-ncar.s3.data.neonscience.org/NEON/atm/cdeps/v1/KONA/KONA_missing.pdf)
- Nothing's jumping out of the [forcing data either](https://neon-ncar.s3.data.neonscience.org/NEON/atm/cdeps/v1/KONA/KONA_forcing.pdf), but it did get really cold this winter (same period as Texas freeze?).   

@negin513 and @danicalombardozzi  any idea why this run may be failing?

**Comment by wwieder** [comment] 2021-09-22 12:44
The other surface data issue is with STER, which prints the following ERROR: `surfrd_veg_all ERROR: sum of wt_nat_patch not    1.0 at nl=1 sum is:   0`. Is this supposed to  be an ag site? If so, what do we need to do to correct this error?

**Comment by wwieder** [comment] 2021-09-30 20:41
@negin513 I'll add this note on ABBY here
- [ ] Corrected data for ABBY soil properties should be changed in the surface data.  Measurements for two samples were switched in the raw data from NEON.  Until this is corrected ABBY soil properties should be as follows: 
- carbonTot, nitrogenTot, sulfurTot, estimatedOC (g / kg):
- AB: 49.2, 3.0, 0.2, 49
- Bw1: 21.8, 1.4, 0.1, 22

**Comment by wwieder** [comment] 2021-09-30 20:43
- [ ] surface data should use calculated OC, using CaCO3 measurements, not the `estimatedOC` provided by NEON, which is rounded to the nearest integer.

**Comment by ekluzek** [comment] 2021-12-16 07:41
@negin513 and @wwieder I think all of these are taken care of in @negin513 contributions in ctsm5.1.dev067. Could you double check and close this if so?

**Comment by wwieder** [comment] 2021-12-16 12:55
Yes, it looks like the issues above were resolved by @negin513 in #1539.

**Closed** 2021-12-17 13:33 UTC
Labels: type: bug
