### ISSUE TITLE
svn checkout issue during manage_externals

### ISSUE THREAD

**Issue by pnlfang** [ESCOMP/ctsm#362] opened 2018-05-02 14:20 UTC
My problem is that when running ./manage_externals/checkout_externals on PNNL's constance machine, I encounter an SVN authentication request which will not authenticate.

I am aware that there is a public password associated with guestuser, which I tried, it is possible I do not have the current/correct one.  I checked in with @rgknox and he has not seen this prompt before.:

```
[d3m045@constance01 ctsm]$ ./manage_externals/checkout_externals 
Processing externals description file : Externals.cfg
Processing externals description file : Externals_CISM.cfg
Processing externals description file : Externals_CLM.cfg
Checking status of externals: cism, source_cism, clm, fates, ptclm, mosart, cime, rtm, 
Checking out externals: cism, clm, mosart, cime, rtm, 
Processing externals description file : Externals_CISM.cfg
Checking out externals: source_cism, Password for 'guestuser': 

ERROR: Failed with output:
    Authentication realm: <https://svn-ccsm-models.cgd.ucar.edu:443> ccsm:models
    svn: Server sent unexpected return value (403 Forbidden) in response to OPTIONS request for 'https://svn-ccsm-models.cgd.ucar.edu/cism/branch_tags/longer_var_list_tags/longer_var_list_n01_cism2_1_develop_n02'

ERROR: In directory
    /pic/projects/ngee_tropics/d3m045/ctsm
Process did not run successfully; returned status 1:
    svn checkout --quiet https://svn-ccsm-models.cgd.ucar.edu/cism/branch_tags/longer_var_list_tags/longer_var_list_n01_cism2_1_develop_n02 /pic/projects/ngee_tropics/d3m045/ctsm/components/cism/glimmer-cism
See above for output from failed command.
Please check the log file manage_externals.log for more details.
[d3m045@constance01 ctsm]$ svn ls https://svn-ccsm-models.cgd.ucar.edu --
Authentication realm: <https://svn-ccsm-models.cgd.ucar.edu:443> ccsm:models
Password for 'guestuser': 

-----------------------------------------------------------------------
ATTENTION!  Your password for authentication realm:

   <https://svn-ccsm-models.cgd.ucar.edu:443> ccsm:models

can only be stored to disk unencrypted!  You are advised to configure
your system so that Subversion can store passwords encrypted, if
possible.  See the documentation for details.

You can avoid future appearances of this warning by setting the value
of the 'store-plaintext-passwords' option to either 'yes' or 'no' in
'/people/d3m045/.subversion/servers'.
-----------------------------------------------------------------------
Store password unencrypted (yes/no)? yes
svn: Server sent unexpected return value (403 Forbidden) in response to PROPFIND request for '/!svn/bc/89113'
```

**Comment by ekluzek** [comment] 2018-05-02 14:34
@pnlfang this is a known issue that comes in for the latest version of CLM. We do know about it and are working on it. Until we get it corrected the only workaround is to have a username/password for our CESM developers repository. You could apply here...

https://csegweb.cgd.ucar.edu/svnuser/cgi-bin/repo_access_form.cgi

The other workaround is to use a version of CLM before the one with this issue clm5.0.dev007. So use clm5.0.dev006 or earlier.

We will get a version of cism that's in git in a few weeks, so once that happens and we bring it to a CLM tag you won't run into this problem.

**Comment by billsacks** [comment] 2018-05-02 14:36
I'm hoping to have a new cism tag ready within the next week. Sorry for the inconvenience. I'm going to close this issue since it will be fixed soon..

**Comment by billsacks** [comment] 2018-05-02 14:39
Actually, I'll keep this open until we actually bring in the new cism version.

**Comment by ekluzek** [comment] 2018-05-02 15:00
@billsacks I was going to suggest the same, that we keep it open until we have the fix in a CTSM version.

**Comment by ekluzek** [comment] 2018-05-14 22:30
This will be done in clm5.0.dev010 which will have a version of cism, that doesn't point to a svn repo, but a git repo.

**Comment by ekluzek** [comment] 2018-05-15 15:59
Fixed in clm5.0dev010

**Closed by ekluzek** 2018-05-15 15:59 UTC
Labels: priority: high

**Comment by KingLLee** [comment] 2022-04-07 06:50
Today, i tried to download the cesm2.1.3, but it warns me that:
 ERROR: In directory
    D:\Document\CODE_GITHUB\my_cesm_sandbox
Process did not run successfully; returned status 1:
    svn checkout --quiet https://svn-ccsm-models.cgd.ucar.edu/tools/proc_atm/chem_proc/release_tags\chem_proc5_0_03_rel D:\Document\CODE_GITHUB\my_cesm_sandbox\components\cam\chem_proc
See above for output from failed command.

ERROR:root:Failed with output:
    svn: E170013: Unable to connect to a repository at URL 'https://svn-ccsm-models.cgd.ucar.edu/tools/proc_atm/chem_proc/release_tags%5Cchem_proc5_0_03_rel'
    svn: E215004: No more credentials or we tried too many times.
    Authentication failed
--------------------------------------------------------------------------------------------------------
And I tried to open the url"https://svn-ccsm-models.cgd.ucar.edu/tools/proc_atm/chem_proc/release_tags%5Cchem_proc5_0_03_rel", but this website needs to login. I don't have the username and password.
Please give me some advice to solve this problem. Thank you.

**Comment by billsacks** [comment] 2022-04-07 14:46
I think this may be an issue with manage_externals on Windows. Can you please try:

```
svn checkout --quiet https://svn-ccsm-models.cgd.ucar.edu/tools/proc_atm/chem_proc/release_tags/chem_proc5_0_03_rel D:\Document\CODE_GITHUB\my_cesm_sandbox\components\cam\chem_proc
```

**Comment by KingLLee** [comment] 2022-04-07 15:25
> I think this may be an issue with manage_externals on Windows. Can you please try:
> 
> ```
> svn checkout --quiet https://svn-ccsm-models.cgd.ucar.edu/tools/proc_atm/chem_proc/release_tags/chem_proc5_0_03_rel D:\Document\CODE_GITHUB\my_cesm_sandbox\components\cam\chem_proc
> ```

Thank you very much about that, and I may find the problem of that:
```
[carma]
local_path = src/physics/carma/base
protocol = svn
repo_url = https://svn-ccsm-models.cgd.ucar.edu/carma/release_tags
tag = carma3_49_rel
required = True

[clubb]
local_path = src/physics/clubb
protocol = git
repo_url = https://github.com/ESCOMP/CLUBB_CESM
tag = vendor_clubb_r8099_n03
required = True
```
The problem happens when the '/' can be used in the linux , but not work in the windows, so I'll try again to install cesm2 in my linux virtual machine. Thank you very much.

**Comment by billsacks** [comment] 2022-04-07 15:38
Sounds good. If you want to try to get this working on Windows, I believe the changes in manage_externals/manic/repository_svn.py here https://github.com/ESMCI/manage_externals/pull/167/files should fix this problem. I don't have a Windows machine to test on, so if you are able to test this out, I'd be interested to know if it solves your problem.

**Comment by billsacks** [comment] 2022-04-07 15:44
(It may be that there are other problems on Windows besides just the above one. I see your point that the local_paths include '/', which is not the correct separator on Windows, but I think if that were causing problems you would have seen a different and earlier error when running checkout_externals.)

**Comment by KingLLee** [comment] 2022-04-08 07:08
> Sounds good. If you want to try to get this working on Windows, I believe the changes in manage_externals/manic/repository_svn.py here https://github.com/ESMCI/manage_externals/pull/167/files should fix this problem. I don't have a Windows machine to test on, so if you are able to test this out, I'd be interested to know if it solves your problem.

Yes, It work, and windows machine can successfully download the cesm-release by doing so. Thank you very much. :smiley:

**Comment by billsacks** [comment] 2022-04-08 13:32
Great, thanks for testing it and letting me know!

**Comment by KingLLee** [comment] 2022-04-09 01:34
That's ok, I'm studying in the relevant field 😄 . And another question, can I just copy my downloaded cesm code to linux machine and run it successfully if the linux machine has entire environment variables that the cesm needs?

**Comment by billsacks** [comment] 2022-04-09 16:39
I'm not exactly sure what you're asking, but see https://escomp.github.io/CESM/versions/master/html/introduction.html#cesm2-software-operating-system-prerequisites and https://esmci.github.io/cime/versions/master/html/users_guide/porting-cime.html .

**Comment by KingLLee** [comment] 2022-04-10 01:02
OK, I'll try later. Thank you.

**Comment by KingLLee** [comment] 2022-04-28 09:01
I recently ported and validated the cime on my platform, but met with two questions below:
* ONE:
```
./create_newcase --case F2000climo.test --compset 2000_CAM60_CLM50%SP_CICE%PRES_DOCN%DOM_MOSART_CISM2%NOEVOLVE_SWAV  --res f09_f09_mg17 --machine HUAN
ERROR: No machine HUAN found
```
* TWO
I configure my machine file: conf_machine.xml in my home/.cime, and I have problems running scripts_regression_tests.py:
```
FileNotFoundError: [Errno 2] No such file or directory: '/public/home/atm01/release-cesm2.2.0/cime/config/e3sm/machines/config_machines.xml'
```
But what makes me wonder is that I don't need to model e3sm.
How to solve these problems?

**Comment by billsacks** [comment] 2022-04-28 17:04
For problem 2, there are a number of ways to tell CIME that you're using CESM. My preferred way is to set the environment variable CIME_MODEL=cesm.

For problem 1 and any other problems you are having with porting, please post your issue to the CESM forums: https://bb.cgd.ucar.edu/cesm/forums/infrastructure-cime-porting-machines-scripts.132/ . Please be sure to include details of what you did for your machine port. See https://bb.cgd.ucar.edu/cesm/threads/information-to-include-in-help-requests.4974/ for a list of what to provide in the help request.
