### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by rosiealice** [ESCOMP/ctsm#258] opened 2018-02-06 22:33 UTC
I just tweeted the existence of this repo...
https://twitter.com/CLM_science

Someone suggested writing a 'code of conduct' to facilitate development. Should we do that?

**Comment by serbinsh** [comment] 2018-02-06 22:46
Not exactly a code of conduct but here is what we have for info on contributing to PEcAn https://github.com/PecanProject/pecan/blob/develop/CONTRIBUTING.md

It’s probably worth while putting something in writing that describes how you envision contributions and development activities.

Shawn

Sent from my iPhone

On Feb 6, 2018, at 5:33 PM, rosiealice <notifications@github.com<mailto:notifications@github.com>> wrote:


I just tweeted the existence of this repo...
https://twitter.com/CLM_science

Someone suggested writing a 'code of conduct' to facilitate development. Should we do that?

**Comment by jhamman** [comment] 2018-02-06 22:47
Mostly just watching what goes on here but I'll pipe in to share a few things I've learned while helping manage open-source projects on GitHub.

1. For a code of conduct, consider starting with something like the [Contributor Covenant](https://www.contributor-covenant.org/version/1/4/code-of-conduct.html)). This is less about facilitating actual development and more about facilitating a functional open-source community. Often times, projects just take the CC Contributor Covenant directly. These usually go in a `CODE_OF_CONDUCT.md` file at the top of the repository ([example](https://github.com/pydata/xarray/blob/master/CODE_OF_CONDUCT.md)).
2. Add a contributors guide (`CONTRIBUTING.md`) that discusses the process of contributing to CTSM development, governance, support, etc. This might look something like [this](https://github.com/UW-Hydro/VIC/blob/master/.github/CONTRIBUTING.md).

**Comment by serbinsh** [comment] 2018-02-06 22:48
Actually, I forgot we do have this as well:  https://pecanproject.github.io/pecan-documentation/master/contributor-covenant-code-of-conduct.html

Sent from my iPhone

On Feb 6, 2018, at 5:33 PM, rosiealice <notifications@github.com<mailto:notifications@github.com>> wrote:


I just tweeted the existence of this repo...
https://twitter.com/CLM_science

Someone suggested writing a 'code of conduct' to facilitate development. Should we do that?

**Comment by rosiealice** [comment] 2018-02-07 00:12
Thanks for the input, and also for being our first open source contributors, @jhamman and @serbinsh  :D We're all in a meeting all week, but this is super useful.

**Comment by billsacks** [comment] 2018-02-07 13:44
See also some links in #227 . This issue is a duplicate of that, but I'll keep this one open, too, because there is some useful discussion here. Thanks @serbinsh and @jhamman for the pointers!

**Closed** 2018-02-13 16:44 UTC
Labels: type: docs - non-code
